# Generated by Django 3.1.4 on 2021-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210510_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNISEX')], default='M', max_length=1),
        ),
    ]
