# Generated by Django 3.1.4 on 2021-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'MENS SHIRTS'), ('MT', 'MENS T-SHIRTS'), ('MJ', 'MENS JEANS'), ('MCS', 'MENS CASUAL SHOES'), ('MSS', 'MENS SPORTS SHOES'), ('MCO', 'MENS CLOTHES OTHERS'), ('MSO', 'MENS SHOES OTHERS'), ('WS', 'WOMENS SHIRTS'), ('WT', 'WOMENS T-SHIRTS'), ('WJ', 'WOMENS JEANS'), ('WCS', 'WOMENS CASUAL SHOES'), ('WSS', 'WOMENS SPORTS SHOES'), ('WCO', 'WOMENS CLOTHES OTHERS'), ('WSO', 'WOMENS SHOES OTHERS')], max_length=3),
        ),
    ]
